CREATE INDEX IF NOT EXISTS "users_tenant_id_idx" ON "inspirapos_v2"."users" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sessions_user_id_idx" ON "inspirapos_v2"."sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sessions_expires_at_idx" ON "inspirapos_v2"."sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "otp_codes_user_id_code_idx" ON "inspirapos_v2"."otp_codes" USING btree ("user_id","code");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "password_reset_tokens_user_id_idx" ON "inspirapos_v2"."password_reset_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenants_deleted_at_idx" ON "inspirapos_v2"."tenants" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenants_status_idx" ON "inspirapos_v2"."tenants" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "outlets_tenant_id_idx" ON "inspirapos_v2"."outlets" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customers_tenant_id_idx" ON "inspirapos_v2"."customers" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "offline_clients_deleted_at_idx" ON "inspirapos_v2"."offline_clients" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "offline_licenses_client_id_idx" ON "inspirapos_v2"."offline_licenses" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leads_deleted_at_idx" ON "inspirapos_v2"."leads" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leads_status_idx" ON "inspirapos_v2"."leads" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_notes_lead_id_idx" ON "inspirapos_v2"."lead_notes" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "billing_records_tenant_id_idx" ON "inspirapos_v2"."billing_records" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "admin_audit_logs_created_at_idx" ON "inspirapos_v2"."admin_audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "categories_tenant_id_idx" ON "inspirapos_v2"."categories" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "menus_tenant_id_category_id_idx" ON "inspirapos_v2"."menus" USING btree ("tenant_id","category_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "variant_groups_tenant_id_idx" ON "inspirapos_v2"."variant_groups" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "variant_options_group_id_idx" ON "inspirapos_v2"."variant_options" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "menu_variant_groups_menu_id_idx" ON "inspirapos_v2"."menu_variant_groups" USING btree ("menu_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "menu_variant_groups_variant_group_id_idx" ON "inspirapos_v2"."menu_variant_groups" USING btree ("variant_group_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "stock_levels_tenant_id_idx" ON "inspirapos_v2"."stock_levels" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pos_shifts_tenant_id_status_idx" ON "inspirapos_v2"."pos_shifts" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pos_orders_tenant_id_created_at_idx" ON "inspirapos_v2"."pos_orders" USING btree ("tenant_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pos_orders_shift_id_idx" ON "inspirapos_v2"."pos_orders" USING btree ("shift_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pos_order_items_order_id_idx" ON "inspirapos_v2"."pos_order_items" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "restaurant_tables_tenant_id_idx" ON "inspirapos_v2"."restaurant_tables" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "kitchen_tickets_tenant_id_status_idx" ON "inspirapos_v2"."kitchen_tickets" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ingredients_tenant_id_idx" ON "inspirapos_v2"."ingredients" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "recipe_items_tenant_id_menu_id_idx" ON "inspirapos_v2"."recipe_items" USING btree ("tenant_id","menu_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "branch_transfers_tenant_id_idx" ON "inspirapos_v2"."branch_transfers" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "branch_transfer_items_transfer_id_idx" ON "inspirapos_v2"."branch_transfer_items" USING btree ("transfer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "loyalty_members_tenant_id_phone_idx" ON "inspirapos_v2"."loyalty_members" USING btree ("tenant_id","phone");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "loyalty_point_logs_tenant_id_member_id_idx" ON "inspirapos_v2"."loyalty_point_logs" USING btree ("tenant_id","member_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "loyalty_broadcasts_tenant_id_idx" ON "inspirapos_v2"."loyalty_broadcasts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "attendance_logs_tenant_id_date_idx" ON "inspirapos_v2"."attendance_logs" USING btree ("tenant_id","date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "operational_expenses_tenant_id_spent_at_idx" ON "inspirapos_v2"."operational_expenses" USING btree ("tenant_id","spent_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ingredient_waste_logs_tenant_id_idx" ON "inspirapos_v2"."ingredient_waste_logs" USING btree ("tenant_id");